Repository o365soa/soa, pull requests merged in 2024-10, with the labels that each got.

#108 Add undocumented Teams SKU
  SOA/resources.json
Labels: bug

#109 Remove ISE block
  SOA/SOA-Prerequisites.psm1
Labels: enhancement

#110 Update GitHub action to use Node.js 20
  .github/workflows/psgallery.yml
Labels: ignore-for-release

#111 Add better description to module manifest
  SOA/SOA.psd1
Labels: ignore-for-release

#107 Remove legacy functions from module
  SOA/SOA-Prerequisites.psm1
  SOA/SOA.psd1
Labels: enhancement

#114 Update Markdown formatting
  README.md
Labels: ignore-for-release

#112 Move license SKUs to resources file
  SOA/SOA-Prerequisites.psm1
  SOA/resources.json
Labels: enhancement
